image: maven:3.3.3

pipelines:
  default:
    - step:
        size: 2x # Double resources available for this step.
        script:
          - cd symja_android_library && mvn clean install -pl matheclipse-core